### PR TITLE
Cosmetic fix for /editor/posts

### LINKED ISSUE #362: 非公開の記事は一覧ではグレーアウトされていてほしい

### PR DESCRIPTION
**Pull request by okkez**
- Add column to display published/unpublished
- Unpublished posts are gray out

Close #362

### CODE REVIEW

**Comment by okkez** [comment]
こんな感じになった。
screenshot from 2016-03-23 09-15-33

**Comment by okkez** [comment]
Use BEM same as `/admin/sites`

**Comment by tricknotes** [comment]
Ouch! https://github.com/bm-sms/daimon-news-multi-tenant/pull/393#issuecomment-200613810 とコンフリクトしてしまったので rebase お願いしますー :pray:

**Comment by okkez** [comment]
:ok_woman:

**Comment by okkez** [comment]
Rebased

**Pull request merged**
