### PR TITLE
Remove `Post#to_param`

### LINKED ISSUE #538: Remove `Post#to_param`
We should specify `public_id` to `post_url` explicitly.

### PR DESCRIPTION
**Pull request by okkez**
Close #538

### CODE REVIEW

**Comment by okkez** [comment]
We decided to stop using `Post#to_param`.
Because it has global effect against whole this application.

We can specify `public_id` explicitly to `post_url` and `post_path`.

**Comment by myokoym** [comment]
Looks good :+1:

Note: For API: #537

**Comment by okkez** [comment]
Rebased

**Comment by tricknotes** [comment]
It works 🚢

**Pull request merged**
