### PR TITLE
Clear layout related to devise/sessions

### LINKED ISSUE #480: Unpublished site displays recent posts in sidebar
Displays category names, too. See #360

### PR DESCRIPTION
**Pull request by okkez**
See https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts

Close #480

### CODE REVIEW

**Comment by okkez** [comment]
Changed like:

screenshot from 2016-04-27 17-56-45

**Comment by okkez** [comment]
Added `current_site.fqdn`.

screenshot from 2016-04-28 12-29-45

**Comment by myokoym** [comment]
Looks good!

**Comment by myokoym** [comment]
:shipit:

**Pull request merged**
