### PR TITLE
Sitemap

### PR DESCRIPTION
**Pull request by tricknotes**
Close https://github.com/bm-sms/daimon-news-multi-tenant/issues/48

### CODE REVIEW

**Comment by tricknotes** [comment]
It works for me

**Comment by tricknotes** [comment]
To  update `sitemap.xml`, run the following task:

``` sh
$ heroku run rake daimon:update_all_sitemap
```

**Comment by mtsmfm** [comment]
:shipit: :star2:

**Comment by tricknotes** [comment]
:ship:

**Pull request merged**
