### PR TITLE
Use daimon-markdown

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
Differences:
- Redcarpet replaces HTML literals to HTML entities, but Nokogiri replaces HTML entities to HTML literals
- Inserted some line breaks, but HTML semantics is not changed

We can merge this PR and ship it to production, I think.

**Comment by tricknotes** [comment]
TODO
- [ ] We consider preview page.
- [ ] We should check rendered HTML that is not broken.

---
- [ ] preview 画面は JS で独自に MArkdown をパースしているので、なにかやりかたを変えないとまずそう
- [ ] この PR をマージした結果、現在表示されている HTML を壊さないことの検証をしたいですね！

**Comment by okkez** [comment]
> We consider preview page.

We have not considered preview on markdown-editor.
BTW, we should implement real preview on markdown-editor.

> We should check rendered HTML that is not broken.

I've checked all generated HTML contents.
You can check it using scripts/dump_html.rb.

**Comment by okkez** [comment]
Could you tell me how to confirm that generated HTML is broken or not?
I have no idea for now.

**Comment by mtsmfm** [comment]
:shipit:

**Pull request merged**
