### PR TITLE
Use kramdown instead of redcarpet

### LINKED ISSUE #214: Support syntax highlight
Use rouge
https://github.com/jneen/rouge

### LINKED ISSUE #221: オートリンクが無効
Related to #214

### PR DESCRIPTION
**Pull request by okkez**
Use GFM!
Close #221
Close #214

### CODE REVIEW

**Comment by okkez** [comment]
Rebased

**Comment by okkez** [comment]
Table syntax is ok.

**Comment by okkez** [comment]
Add autolink :yum:

**Comment by tricknotes** [comment]
Do you like test code?

**Comment by okkez** [comment]
YES I DO.

**Comment by tricknotes** [comment]
Could you add the test case for following URLs?
- `http://example.com/foo_bar_baz` (including `_`)
- `http://example.com/foo\_bar\_baz` (including `\_`)

Because autolink changes the rendering behavior.
- `http://example.com/foo_bar_baz`
  - Before: `<p>http://example.com/foo<em>bar</em>baz</p>`
  - After: `<p><a href="http://example.com/foo_bar_baz">http://example.com/foo_bar_baz</a></p>`
- `http://example.com/foo\_bar\_baz`
  - Before: `<p>http://example.com/foo_bar_baz</p>`
  - After: `<p><a href=\"http://example.com/foo\\_bar\\_baz\">http://example.com/foo\\_bar\\_baz</a></p>`

I think this change should be documented as test code.

**Comment by okkez** [comment]
Thanks in advance.
I will add such test case.

**Comment by okkez** [comment]
We use Redcarpet.

**Pull request closed without merging**
